### PR TITLE
Front end programming languages

### PR DESCRIPTION
**Pull request by variable24**
@OlegMitsik @mrangel86 Check out my file. Let me know if you have any feedback for me.

### CODE REVIEW

**Comment by mrangel86** [comment]
Hey @variable24 looks like a good start, but let's add some more detail?

Pretend someone didn't know what these names meant.

**Comment by variable24** [comment]
@mrangel86 :+1: Good idea. I will work on it.

**Comment by variable24** [comment]
@mrangel86 @OlegMitsik I added more descriptions to the terms. Can you guys take a look and let me know if it's okay

**Comment by mrangel86** [comment]
Awesome --- looks great to me man.

I give it the :+1: 

Just waiting on @OlegMitsik feedback!

**Comment by mrangel86** [comment]
Awesome --- merging now!

Thanks!

**Pull request merged**
